/*
 * (c) copyright 1987 by the Vrije Universiteit, Amsterdam, The Netherlands.
 * See the copyright notice in the ACK home directory, in the file "Copyright".
 */
/* $Header: errlist.c,v 1.1 89/05/10 16:22:20 eck Exp $ */

#include	<errno.h>

static const char unknown[] = "Unknown error";

const char *_sys_errlist[] = {
        "Error 0",
        "Not owner",
        "No such file or directory",
        "No such process",
        "Interrupted system call",
        "I/O error",
        "No such device or address",
        "Arg list too long",
        "Exec format error",
        "Bad file number",
        "No children",
        "No more processes",
        "Not enough core",
        "Permission denied",
        "Bad address",
        "Block device required",
        "Resource busy",
        "File exists",
        "Cross-device link",
        "No such device",
        "Not a directory",
        "Is a directory",
        "Invalid argument",
        "File table overflow",
        "Too many open files",
        "Not a typewriter",
        "Text file busy",
        "File too large",
        "No space left on device",
        "Illegal seek",
        "Read-only file system",
        "Too many links",
        "Broken pipe",
        "Math argument",
        "Result too large",
	"Resource deadlock avoided",
	"File name too long",
	"No locks available",
	"Function not implemented",
	"Directory not empty",
	/*40*/unknown,
	/*41*/unknown,
	/*42*/unknown,
	/*43*/unknown,
	/*44*/unknown,
	/*45*/unknown,
	/*46*/unknown,
	/*47*/unknown,
	/*48*/unknown,
	/*49*/unknown,
	"Invalid packet size",
	"Not enough buffers left",
	"Illegal ioctl for device",
	"Badmode for ioctl",
	"Would block",
	"Bad destination address",
	"Destination not reachable",
	"All ready connected",
	"Address in use",
	"Connection refused",
	"Connection reset",
	"Connection timed out",
	"Urgent data present",
	"No urgent data present",
	"No connection",
	"Allready shutdown",
	"No such connection",
};

const int _sys_nerr = sizeof(_sys_errlist) / sizeof(_sys_errlist[0]);
